#!/usr/bin/env bash

# Config helper.

# Exit on error.
set -e

# Shows the output of every command
set +x

# Color settings
Bold='\033[1m'
BRed='\033[1;31m'
BGreen='\033[1;32m'
NC='\033[0m' # No Color

# Log an error.
err() {
    printf "${BRed}Error${NC}: $1\n" >&2
    exit 1
}

# Log info.
info() {
    printf "${BGreen}Info${NC}: $1\n" >&1
}

# Run a command that should never fail. If the command fails execution
# will immediately terminate with an error showing the failing
# command.
ensure() {
    if ! "$@"; then err "command failed: $*"; fi
}

copy_hyprland_config() {
    ensure cp ./hypr/hyprland.conf ~/.config/hypr/hyprland.conf
    info "Copied Hyprland configuration file."
}

main() {
    case $1 in
        "hypr")
            copy_hyprland_config;;
        *)
            echo 'Expected "hypr".';;
    esac
}

main "$@" || exit 1
