#!/usr/bin/env bash

# Config helper.

# Exit on error.
set -e

# Shows the output of every command
set +x

# Color settings
Bold='\033[1m'
BRed='\033[1;31m'
BGreen='\033[1;32m'
NC='\033[0m' # No Color

# Log an error.
err() {
    printf "${BRed}Error${NC}: $1\n" >&2
    exit 1
}

# Log info.
info() {
    printf "${BGreen}Info${NC}: $1\n" >&1
}

# Run a command that should never fail. If the command fails execution
# will immediately terminate with an error showing the failing
# command.
ensure() {
    if ! "$@"; then err "command failed: $*"; fi
}

copy_hyprland_config() {
    ensure mkdir -p ~/.config/hypr
    ensure cp ./config/hyprland.conf ~/.config/hypr/hyprland.conf
    info "Copied Hyprland configuration file."
}

copy_waybar_config() {
    ensure mkdir -p ~/.config/waybar
    ensure cp ./config/waybar.conf ~/.config/waybar/config
    info "Copied Waybar configuration."
}

copy_wallpaper() {
    local wallpaper_filename=".wallpaper"
    case $1 in
        "musashi")
            cp ./wallpapers/miyamoto-musashi.png ~/$wallpaper_filename
            info "Copied miyamoto-musashi wallpaper."
            ;;
        "nixos")
            cp ./wallpapers/nixos_honeycombs.png ~/$wallpaper_filename
            info "Copied nixos_honeycombs wallpaper."
            ;;
        *)
            echo 'Expected "musashi", "nixos".';;
    esac
}

copy_hyprpaper() {
    ensure mkdir -p ~/.config/hypr
    ensure cp ./config/hyprpaper.conf ~/.config/hypr/hyprpaper.conf
    info "Copied Hyprpaper configuration file."
}

main() {
    case $1 in
        "hypr")
            copy_hyprland_config;;
        "waybar")
            copy_waybar_config;;
        "wallpaper")
            copy_wallpaper $2;;
        "paper")
            copy_hyprpaper;;
        *)
            echo 'Expected "hypr", "waybar", "wallpaper", "paper".';;
    esac
}

main "$@" || exit 1
